--- 
- hosts: 172.31.23.86
  become: yes
  tasks:
  - copy: src=/etc/group
          dest=/tmp
          owner=ravi
          group=ravi
          mode=0664
  - file: path=/tmp/gcp
          state=directory
  - apt:  name=apache2
          state=present
                       


