---
- hosts: 172.31.15.98
  become: yes
  tasks: 
  - include_tasks: myfile.yml
  - name: create a myfolder
    file:
     path: /home/ubuntu/myfolder
     state: directory
  - name: copy file form moster to node
    copy:
     src: my10thfile.txe
     dest: /home/ubuntu/my10thfile
  - name: install apache2
    apt:
     name: apache2
     state: present
  - name: copy dynamic file into  side
    template:
     src: myindex.j2
     dest: /var/www/html/index.html
 
     