---
- hosts: mywebservers
  become: yes
  tasks:
   - name: i want to install apache2 on ubuntu ansible nodes
     apt:
      name: "{{mywebpackonubuntu}}"
      state: present
     when: ansible_os_family=="Debian"
   - name: i want to start apache2 webserver
     service: 
      name: "{{mywebpackonubuntu}}"
      state: started
     when: ansible_os_family=="Debian"
   
   - name: i want to install webserver on RedHat
     yum: 
      name: "{{mywebserveronredhat}}"
      state: present
     when: ansible_os_family=="RedHat"
   - name: i want to start webserver on RedHat
     service: 
      name: "{{mywebserveronredhat}}"
      state: started
     when: ansible_os_family=="RedHat"

